[2022-07-16 17:15:31,281] {processor.py:153} INFO - Started process (PID=1397) to work on /opt/airflow/dags/python_op.py
[2022-07-16 17:15:31,297] {processor.py:641} INFO - Processing file /opt/airflow/dags/python_op.py for tasks to queue
[2022-07-16 17:15:31,310] {logging_mixin.py:115} INFO - [2022-07-16 17:15:31,308] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/python_op.py
[2022-07-16 17:15:31,424] {logging_mixin.py:115} INFO - [2022-07-16 17:15:31,377] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/python_op.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/python_op.py", line 5, in <module>
    with DAG(
TypeError: __init__() missing 1 required positional argument: 'dag_id'
[2022-07-16 17:15:31,428] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/python_op.py
[2022-07-16 17:15:31,788] {processor.py:161} INFO - Processing /opt/airflow/dags/python_op.py took 0.852 seconds
